name: CI

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - '**/*.txt'
      - '**/*.png'
      - '**/*.jpg'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - '**/*.txt'
      - '**/*.png'
      - '**/*.jpg'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create local.properties
        run: |
          echo "CLIENT_ID=\"${{ secrets.CLIENT_ID }}\"" >> local.properties
          echo "CLIENT_SECRET=\"${{ secrets.CLIENT_SECRET }}\"" >> local.properties
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 24
      - uses: gradle/actions/setup-gradle@v4
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace
